[build]
  publish = "."

[[headers]]
  for = "/downloads/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Disposition = "attachment"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
